# Generated by Django 5.1.7 on 2025-03-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('weather_datas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherDate',
            new_name='WeatherData',
        ),
    ]
